services:
  web_server:
    build:
      context: recruto
      dockerfile: Dockerfile
      target: builder
    ports:
      - '8000:8000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build:
      context: web
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"

  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - "6379:6379"