# Generated by Django 5.1.1 on 2024-09-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=50)),
                ('expected_salary', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('source_url', models.CharField(default='NA', max_length=200)),
            ],
        ),
    ]
